before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: RfvA99Em39IMolTmn+W29OFR0FXqpJlt8YY4jNB2ADrdAXYW9ft5csdVxCxsON+X9MoBTlSnzXcnadLGttDrq2UsdE+xaS1OKm04wbju2edaCiCXUJxs/oRTIroOuwe+HurImZ12oH9jyVn7t6hOlVJMIPtOQGcEeUGP+kljWyegTKWYTVHlVQ3ZL+78bGTyL5YPg7zJ2CZ+edistLVbps/NApE8GWmymyUXCQb7rKBStIsJX8QFkx57+GrfOy5BbTpVZiE4hDyi11NKFf09r5ZiBsy25K8w5nVf/AuNnQi6SsYZWMsFE9AGFA826oP+7zBdcyeO+NWymk7bPHGpxuUCkKhcbNn/oTpAW4m6QMFAYhx/eY+bc/OxB4ASNrQTB1jtVXmL4VFJrXG3bNH/kHOGPXnkDK+kxjWf8ZoewsbDwUfGCIWNbry/n1abfzlQU1Nj+AlWyKxwkH3cMYFsZeUoa/gJ0Kd/G/OjmBJLfR9b74OiBRFVTIBiUOXBt7M/xaF6rj4gQHle0M2jmaUeHxH6J0Aj65mZmbtSMtc4GPnRS8XVXc4H8OWO8eQD2cVluKuCI9iVxeSO3j2gKpha91632OcgRYJms2QFj/kKauVKd1QAENY/GPd6rM+HKNlEKNGHKjjy/z/QdOkEY+BeFmlQ2XhpU/8V45BWsc9lDtI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
